import React, { useEffect, useState } from 'react';
import { Bell, Loader2 } from 'lucide-react';
import { barbershopApi, QueueAlertSettings as QueueAlert } from '../../infra/barbershopApi';
import { getErrorMessage } from '../../utils/errorMessage';
import { maskPhone, normalizePhoneBR } from '../../utils/documentUtils';

export const QueueAlertSettings: React.FC<{ barbershopId: string; onNotify: (message: string, type: 'success' | 'error') => void }> = ({ barbershopId, onNotify }) => {
  const [data, setData] = useState<QueueAlert | null>(null); const [enabled, setEnabled] = useState(false); const [threshold, setThreshold] = useState(10); const [phone, setPhone] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [testing, setTesting] = useState(false);
  useEffect(() => { void barbershopApi.getQueueAlert(barbershopId).then(next => { setData(next); setEnabled(next.enabled); setThreshold(next.threshold); setPhone(next.phone ? maskPhone(next.phone) : ''); }).catch(() => undefined).finally(() => setLoading(false)); }, [barbershopId]);
  const save = async () => { const phoneDigits = normalizePhoneBR(phone); if (threshold < 1 || threshold > 100 || !Number.isInteger(threshold) || (enabled && phoneDigits.length < 10)) { onNotify('Confira o limite e o WhatsApp do alerta.', 'error'); return; } setSaving(true); try { const next = await barbershopApi.updateQueueAlert(barbershopId, { enabled, threshold, phone: phoneDigits || null }); setData(current => current ? { ...current, ...next } : current); onNotify('Alerta de fila salvo.', 'success'); } catch (err) { onNotify(getErrorMessage(err, 'Não foi possível salvar o alerta.'), 'error'); } finally { setSaving(false); } };
  if (loading) return <div className="rounded-xl border border-border bg-surface p-4 text-sm text-text-muted">Carregando alerta de fila…</div>;
  const test = async () => { setTesting(true); try { await barbershopApi.testQueueAlert(barbershopId); onNotify('Teste enviado para o WhatsApp.', 'success'); } catch (err) { onNotify(getErrorMessage(err, 'Não foi possível enviar o teste.'), 'error'); } finally { setTesting(false); } };
  return <section className="rounded-xl border border-border bg-surface p-5" aria-labelledby="queue-alert-title"><div className="flex items-start gap-3"><Bell className="mt-1 text-accent" size={20} /><div><h3 id="queue-alert-title" className="text-lg font-bold text-text-primary">Alerta de fila cheia</h3><p className="mt-1 text-sm text-text-secondary">Receba um aviso quando a fila passar do limite configurado.</p></div></div>{data && !data.queueEnabled && <p className="mt-3 rounded-lg bg-warning/10 p-3 text-xs text-warning">O alerta só funciona quando a fila estiver habilitada no modo de atendimento.</p>}<label className="mt-4 flex min-h-11 items-center gap-3 text-sm font-semibold text-text-primary"><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)} className="h-5 w-5 accent-accent" /> Ativar alerta de fila cheia</label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-text-secondary">Avisar quando passar de<input type="number" min={1} max={100} value={threshold} onChange={e => setThreshold(Number(e.target.value))} className="mt-1 min-h-11 w-full rounded-lg border border-border bg-bg px-3 text-text-primary" /></label><label className="text-xs font-bold text-text-secondary">WhatsApp que receberá o alerta<input value={phone} onChange={e => setPhone(maskPhone(e.target.value))} placeholder="(11) 99999-9999" className="mt-1 min-h-11 w-full rounded-lg border border-border bg-bg px-3 text-text-primary" /></label></div><p className="mt-3 text-xs text-text-muted">Este número pode ser diferente do contato mostrado aos clientes. Você será avisado quando o {threshold + 1}º cliente entrar na fila.</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={() => void save()} disabled={saving} className="flex min-h-11 items-center gap-2 rounded-xl bg-accent px-4 text-sm font-bold text-accent-fg">{saving && <Loader2 size={16} className="animate-spin" />}Salvar alerta</button><button type="button" onClick={() => void test()} disabled={testing || !data?.whatsappConnected} className="min-h-11 rounded-xl border border-border px-4 text-sm font-bold text-text-secondary">{testing ? 'Enviando…' : 'Enviar alerta de teste'}</button></div></section>;
};
